### ISSUE TITLE
Release on PyPI to support latest aiohttp

### ISSUE THREAD

**Issue by iceb0y** [aio-libs/sockjs#105]
sockjs 0.5 doesn't work with aiohttp 2.0.x, but the current head version works. Let's release a 0.6 version.

**Comment by fafhrd91** [comment]
sure, want to do this?

**Comment by iceb0y** [comment]
I think I don't have the permission :joy:

**Comment by fafhrd91** [comment]
I sent you invitation. 
you'll need to bump version and update changes

**Comment by iceb0y** [comment]
done. thanks.
