### ISSUE TITLE
iframe transports not working

### ISSUE THREAD

**Issue by Algy** [aio-libs/sockjs#159]
Communication via iframe transports is broken because of SyntaxError in the embedded html, which is supposed to call `SockJS.bootstrap_iframe()`.

With sockjs server running on port 23299, you can reproduce it with the following stub (Tested in python 3.6.1, Chrome 61 and Firefox 55):
```javascript
SockJS("http://127.0.0.1:23299/sockjs_path", null, {transports: 'iframe-htmlfile'})
>> Uncaught SyntaxError: Invalid or unexpected token iframe.html:9 
```

At line 62 in `protocol.py`, there are leading backslashes before a pair of parentheses where  SyntaxError occurs. To make it work, you can just remove these backslashes.
`    SockJS.bootstrap_iframe\(\);`

**Comment by jettify** [comment]
Good catch! Would you like to submit PR with fix?

**Comment by Algy** [comment]
Done. plz check it out

**Comment by jettify** [comment]
Thanks! Fix merged
