### ISSUE TITLE
Is this project now support?

### ISSUE THREAD

**Issue by pahaz** [aio-libs/sockjs#16]
Hi, I see some opend issuse and pull requests.
Master branch is fail.

Can you tall something about state of this project?

**Comment by fafhrd91** [comment]
i wrote this as an exercise for aiohttp library development. i do not use it production. but it has good test coverage, i think it is fine for production.

**Comment by jettify** [comment]
Issues you are observing, because aiohttp dropped support for python < 3.41. So `.travis.yml` file should be fixed a bit.

**Comment by asvetlov** [comment]
Fixed travis
