### ISSUE TITLE
SessionManager.clear() was never yielded from

### ISSUE THREAD

**Issue by pahaz** [aio-libs/sockjs#21]
Research:
`__del__` at [line](https://github.com/aio-libs/sockjs/blob/b5919acbe525d42e5385ebbe5d4f9ab3aa16470b/sockjs/session.py#L406) call `self.clear()` coroutine [line.](https://github.com/aio-libs/sockjs/blob/b5919acbe525d42e5385ebbe5d4f9ab3aa16470b/sockjs/session.py#L388-L389) 

I think this is quite normal, but I have still some internal question.
What do you think about this? Is this a normal behavior or bug?

**Comment by pahaz** [comment]
When I run my tests I got this warnings:

```
Ran XX tests in 0.906s

OK
<CoroWrapper SessionManager.clear() running at \sockjs\sockjs\session.py:388, created at \sockjs\sockjs\session.py:407> was never yielded from
Coroutine object created at (most recent call last):
  File "\sockjs\sockjs\session.py", line 407, in __del__
    self.clear()
<CoroWrapper SessionManager.clear() running at \sockjs\sockjs\session.py:388, created at \sockjs\sockjs\session.py:407> was never yielded from
Coroutine object created at (most recent call last):
  File "\sockjs\sockjs\session.py", line 407, in __del__
    self.clear()
<CoroWrapper SessionManager.clear() running at \sockjs\sockjs\session.py:388, created at \sockjs\sockjs\session.py:407> was never yielded from
Coroutine object created at (most recent call last):
  File "\sockjs\sockjs\session.py", line 407, in __del__
    self.clear()
...
```

In my code I add this hack for suppress this warning: 
```
    def __del__(self):
        asyncio.new_event_loop().run_until_complete(self.clear())
        # self.clear()
        self.stop()
```

**Comment by asvetlov** [comment]
Good finding!
`run_until_complete()` should be never called from async code, especially with new event loop instance.

May we implement `terminate()` method which cleanups a session manager in hard way without performing graceful shutdown? It should just close a socket without sending close request.

**Comment by masell** [comment]
How about this approach? https://github.com/aio-libs/sockjs/pull/193

Relying on `__del__` alone is not good, as it's not guaranteed to be executed.

Perhaps a async context manager would be better for the future.

**Comment by jersobh** [comment]
As #193  is merged, I'm closing this issue.
