### ISSUE TITLE
Blob

### ISSUE THREAD

**Issue by jersobh** [aio-libs/sockjs#219]
Hi there,

How can I send a blob from sockjs-client to aiohttp-sockjs? I've tryied but there's just [object Blob] result. Right now I'm reading the data with File (window.File, window.FileReader), then encoding to base64, JSON.stringfying it and sending through sockjs, then decoding on server side. But that sometimes corrupts my stream, uses more CPU.. it's not the best way to do it, I guess...
I just need to send a webm file through websockets by chunks, then build it on server side, convert it, whatever.

Thank you, great lib :)

**Comment by novoxudonoser** [comment]
Its a optional experimental feature in [sock.js javascript](https://github.com/sockjs/sockjs-client/issues/252) it not feel so this will be implemented in near future, but pull request may be done.
