### ISSUE TITLE
RawWebSocketTransport reason?

### ISSUE THREAD

**Issue by pahaz** [aio-libs/sockjs#22]
Hi! I check the `sockjs` code and look at `RawWebSocketTransport`.

Confusion:

We have `Session` abstraction and `_remote_message(msg)` coro [link](https://github.com/aio-libs/sockjs/blob/0.4v/sockjs/session.py#L192) which calling on new message from client.

Take a look at `websocket` transport [link](https://github.com/aio-libs/sockjs/blob/0.4v/sockjs/transports/websocket.py#L47-L55)
and `rawwebsocket` transport [link](https://github.com/aio-libs/sockjs/blob/0.4v/sockjs/transports/rawwebsocket.py#L39-L43)
.

As we can see in the first case we pass the `dict` object and in the secon case we pass the `str`.

Next. as we can see [here](https://github.com/aio-libs/sockjs/blob/0.4v/sockjs/transports/__init__.py#L13) the `RawWebSocketTransport` is not a part of the sockjs transports.
And uses as additional route [here](https://github.com/aio-libs/sockjs/blob/0.4v/sockjs/route.py#L81-L83)

I thik that the `RawWebSocketTransport` used for tests or something similar. And this is not a part of the `sockjs` lib.

What is the real purpose of the `RawWebSocketTransport`?

**Comment by pahaz** [comment]
interesting remark: [_remote_message(msg)](https://github.com/aio-libs/sockjs/blob/0.4v/sockjs/session.py#L193) require `str` object. But transports pass the json loaded object (bay be `dict`). 

This is bug or feature?

**Comment by fafhrd91** [comment]
read documentation for https://github.com/sockjs/sockjs-client
