### ISSUE TITLE
Broadcast question

### ISSUE THREAD

**Issue by jersobh** [aio-libs/sockjs#230]
Hi there,

I have a dict like 

companies  = { 
     {
          "company": "test",
         "viewers": []
     },
     {
          "company": "test_2",
         "viewers": []
     },
}

and I append the ws session to the viewers. But when I do like 
for viewer in companies[1]['viewers']:
    test = { 'msg': 'test' }
    viewer.manager.broadcast(resp)

everyone connected to that ws endpoint receives the msg, despite of which company it is.
How can I control this better?

**Comment by JuanjoA** [comment]
Hi, you need to use:

`session.send(msg)`

and not 

`session.manager.broadcast(msg)`

The latter, as its name suggests, is used to send msg to all open sessions.
For more info you can inspect [session.py](https://github.com/aio-libs/sockjs/blob/master/sockjs/session.py)

I hope this helps you.
