### ISSUE TITLE
The library maintainer is wanted

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/sockjs#299]
I don't use the sockjs for 5 years.
I have no time/intention to maintain the library.

We need a champion to pick the flag up.
The biggest problem that I see is the library test suite: it is entirely built on top of aiohttp mocking.
aiohttp envolves, mocks become obsolete, tests fail.
Reliable tests should be rewritten in the functional style, using `aiohttp_client` / `aiohttp_sever` pytest fixtures.
The change is obvious and even relatively easy but tedious: all supported transports are affected.
I have no capacity to do it, but happy to help with review and other support.

If somebody wants to be the project maintainer -- please let me know by a comment for this issue.

**Comment by jersobh** [comment]
I could do that.

**Comment by asvetlov** [comment]
Cool!
Sent you the maintainer invite.
Please feel free to contact me in case of any questions.

**Comment by jersobh** [comment]
I will :)
