### ISSUE TITLE
Increase default session timeout longer than default manager heartbeat interval

### ISSUE THREAD

**Issue by achimnol** [aio-libs/sockjs#38]
Currently `SessionManager`'s default heartbeat is 25 seconds and timeout is 5 seconds.
So if there are no messages for a session within 5 seconds, the connection is closed.

If those are intended defaults, I would like to know why and it should be documented explicitly.
If not, session timeout should become longer than heartbeat intervals by default to avoid confusion of new sockjs package users.

**Comment by asvetlov** [comment]
Ooh. Very sorry for long delay.

Please make a PR.
I believe the timeout should be about 1 min.
Or heartbit should be decreased to 15 secs with 40 secs timeout.
@fafhrd91 ?

**Comment by fafhrd91** [comment]
i am fine

**Comment by iceb0y** [comment]
The 5 seconds timeout was taken from nodejs `disconnect_delay`:
https://github.com/aio-libs/sockjs/commit/b0d7d17646527f89be172c092f9f69c5ffea8a97#diff-c4ae142f5c8b2a63ea9689afef142593

They are different parameters. nodejs `disconnect_delay` means interval to close the transport after client initiates the disconnect but the server does not respond (but it's also used when initiating the connection):
https://github.com/sockjs/sockjs-node/blob/4c9f3009be13962b0785138ccdf527c5abe925f6/lib/session.js

nodejs has a different `heartbeat_delay` for heartbeat, and it's still different from the timeout:
https://github.com/sockjs/sockjs-node/blob/4c9f3009be13962b0785138ccdf527c5abe925f6/lib/transport/websocket.js#L78

This was working fine until the heartbeat behavior silently changed:
https://github.com/aio-libs/sockjs/commit/9c29e9921f815c0146882abab1240cd80473f4ab#diff-c4ae142f5c8b2a63ea9689afef142593R306

**Comment by asvetlov** [comment]
Would you make a PR with the fix?

**Comment by iceb0y** [comment]
What would be the best fix for this? Some options:

1. Simply make `timeout` longer than `heartbeat`.
2. Mimic nodejs client library.
3. Separate heartbeat and timeout, make heartbeat similar to [nats ping/pong](https://nats.io/documentation/internals/nats-protocol/#a-name-pingpong-a-ping-pong).

**Comment by maparent** [comment]
It seems to be worse than that; the call to Session._heartbeat does not seem to call Session._tick, which updates Session.expires. So the session expires at the end of timeout, irrespective of the relative value of timeout and heartbeat. We should make sure _tick is called; I would think right after the dequeue in Session._wait.

**Comment by jersobh** [comment]
Closing this issue since #265 is merged.
