### ISSUE TITLE
sockjs client

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/sockjs#6]
it is very easy to create websocket client, but it might be possible to create other client transports as well.
would anyone use it?

**Comment by asvetlov** [comment]
sockjs clients may be very useful for testing at least.
My desire for aiohttp websocket client was not for usage in my applications but for writing functional tests easy.

**Comment by Lothiraldan** [comment]
+1, at least to be able to use the aiohttp websocket client to validate sockjs application code

**Comment by ariddell** [comment]
You can do this already. Sockjs exposes a websocket at <sockjs_endpoint>/websocket. It's in the sockjs README (https://github.com/sockjs/sockjs-client) under "Connecting to SockJS without the client"

**Comment by Lothiraldan** [comment]
Thank you very much! Will test it using the endpoint then.

**Comment by fafhrd91** [comment]
It is not possible to mimic browser behavior from client. But that seems a lot of work

Отправлено из Outlook




On Wed, Jun 24, 2015 at 12:05 AM -0700, "Boris Feld" <notifications@github.com> wrote:












Thank you very much! Will test it using the endpoint then.
