### ISSUE TITLE
I need to access my custom match_info?

### ISSUE THREAD

**Issue by larry-dev** [aio-libs/sockjs#66]
e.g:
sockjs.add_endpoint(app,chatSession,name='chat',prefix='/chat/{uid:\d+}')

How do i  get  "uid"

**Comment by asvetlov** [comment]
It's impossible now AFAIK.
@fafhrd91 ?

**Comment by fafhrd91** [comment]
it is not possible. but `SessionManager.get(...)` request as parameter, we may pass it to handler as constructor parameter.

**Comment by fafhrd91** [comment]
actually, 
i think we can make `SockJSRoute` overridable then it should be trivial to get match_info

**Comment by asvetlov** [comment]
@fafhrd91 would you make a fix?

**Comment by fafhrd91** [comment]
not in near future.

**Comment by larry-dev** [comment]
I try to add 'self.request=request'in Session class __init__ function.
Will it work?

**Comment by fafhrd91** [comment]
technically you need to handle match_info in this function https://github.com/aio-libs/sockjs/blob/master/sockjs/route.py#L120

**Comment by larry-dev** [comment]
i think it is more flexible to return a request.
i can get request through 'session.request',then get reqeust.match_info and other requests

**Comment by fafhrd91** [comment]
but `session.request` can point to wrong request (not current) in case of various polling transports

**Comment by larry-dev** [comment]
i see.
'session' is not  independent in SessionManager,it is?

**Comment by fafhrd91** [comment]
it is not independent, but session manager can acquire session for different requests

**Comment by larry-dev** [comment]
ok,i see

**Comment by larry-dev** [comment]
thx
