### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by ariddell** [aio-libs/sockjs#7]
I see there's a placeholder on pypi. It would be great to see a preliminary release. (I'd like to use this for testing.)

**Comment by asvetlov** [comment]
@fafhrd91 do you have pending issues?

**Comment by fafhrd91** [comment]
Main functionality is ready, but gc is not implemented. I think it is blocker. But right now I don't have time to complete it. PR anyone? :)

**Comment by asvetlov** [comment]
Please explain #4 first. I may guess what is required but not sure.

My schedule is full but maybe I'll find a time.
Thanks to DataRobot I have 20% time for working on Open Source projects, but now I'm working on aiohttp_security.
Maybe I'll switch to sockjs it I can do it quickly enough.

**Comment by fafhrd91** [comment]
Yes, that's exactly #4. With websockets it is easy but with http based transport it is required.
I may find some time by the end of this week, but at the same time I'd like to work on aiohttp. We'll see
Отправлено из Outlook




On Tue, Jun 9, 2015 at 12:04 PM -0700, "Andrew Svetlov" <notifications@github.com> wrote:












Please explain #4 first. I may guess what is required but not sure.



My schedule is full but maybe I'll find a time.

Thanks to DataRobot I have 20% time for working on Open Source projects, but now I'm working on aiohttp_security.

Maybe I'll switch to sockjs it I can do it quickly enough.

**Comment by asvetlov** [comment]
Got it.
Please tell me how can I help if you will have no chance to finish the issue up to next week.

**Comment by fafhrd91** [comment]
done https://pypi.python.org/pypi/sockjs

**Comment by ariddell** [comment]
Thanks. I'm looking forward to using this.
